services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      [mysqldb]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/cicd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@Admin2024
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=@Admin2024
      - MYSQL_DATABASE=cicd
    ports:
      - 3306:3306
